-- Note: This file was originally generated by Genie

/****
    Purpose: 
             Creates ALL records in RockendAction. i.e. Assumes the table is empty. This isn't really a script which would be added to the build.   
    Notes:   
             Script is created from existing records. 
    Author:       
        Genie

****/


PRINT 'Creating Records in RockendAction...'

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 2  )
 BEGIN

  PRINT 'Creating record for 2.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	2	-- RockendActionID
	, 'OwnerDetails'	-- ActionName
	, 'Rockend.REST.Processor.OwnerInfo'	-- AssemblyName
	, 'OwnerDetails'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 2'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 3  )
 BEGIN

  PRINT 'Creating record for 3.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	3	-- RockendActionID
	, 'OwnerStatement'	-- ActionName
	, 'Rockend.REST.Processor.VBReports'	-- AssemblyName
	, 'OwnerStatement'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 3'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 4  )
 BEGIN

  PRINT 'Creating record for 4.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	4	-- RockendActionID
	, 'TenantDetails'	-- ActionName
	, 'Rockend.REST.Processor.TenantInfo'	-- AssemblyName
	, 'TenantDetails'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 4'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 5  )
 BEGIN

  PRINT 'Creating record for 5.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	5	-- RockendActionID
	, 'OwnerIncomeExpenditure'	-- ActionName
	, 'Rockend.REST.Processor.VBReports'	-- AssemblyName
	, 'OwnerIncomeExpenditure'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 5'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 6  )
 BEGIN

  PRINT 'Creating record for 6.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	6	-- RockendActionID
	, 'TenantLedger'	-- ActionName
	, 'Rockend.REST.Processor.VBReports'	-- AssemblyName
	, 'TenantLedger'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 6'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 7  )
 BEGIN

  PRINT 'Creating record for 7.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	7	-- RockendActionID
	, 'FindUsername'	-- ActionName
	, 'Rockend.REST.Processor.ForgotPassword'	-- AssemblyName
	, 'FindUsername'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 7'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF

 SET IDENTITY_INSERT rmh.RockendAction ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM rmh.RockendAction WHERE  RockendActionID = 8  )
 BEGIN

  PRINT 'Creating record for 8.'
  INSERT 
	rmh.RockendAction
	( 
        RockendActionID
        , ActionName
        , AssemblyName
        , ClassName
	)
  VALUES
	( 
	8	-- RockendActionID
	, 'FindEmail'	-- ActionName
	, 'Rockend.REST.Processor.ForgotPassword'	-- AssemblyName
	, 'FindEmail'	-- ClassName
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 8'
 END


 SET IDENTITY_INSERT rmh.RockendAction OFF
