-- Note: This file was originally generated by Genie

/****
    Purpose: 
             Creates ALL records in DatabaseVersionScriptsRun. i.e. Assumes the table is empty. This isn't really a script which would be added to the build.   
    Notes:   
             Script is created from existing records. 
    Author:       
        Genie

****/


PRINT 'Creating Records in DatabaseVersionScriptsRun...'

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 100  )
 BEGIN

  PRINT 'Creating record for 100.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	100	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, 'NewUpdate.sql'	-- ScriptName
	, '10 Aug 2011 13:21:51'	-- CreatedDate
	, null	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 100'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 101  )
 BEGIN

  PRINT 'Creating record for 101.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	101	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, 'PreviouslyRunUpdate.sql'	-- ScriptName
	, '10 Aug 2011 13:21:51'	-- CreatedDate
	, null	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 101'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 102  )
 BEGIN

  PRINT 'Creating record for 102.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	102	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '003.create.schema.rmh.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 102'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 103  )
 BEGIN

  PRINT 'Creating record for 103.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	103	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '005.create.Tables.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 103'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 104  )
 BEGIN

  PRINT 'Creating record for 104.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	104	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '006.create.procs.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 104'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 105  )
 BEGIN

  PRINT 'Creating record for 105.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	105	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '010.Insert.UserTypes.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 105'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 106  )
 BEGIN

  PRINT 'Creating record for 106.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	106	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '011.Insert.Service.RESTPortal.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 106'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF

 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun ON 


----------------------------------------------------

IF NOT EXISTS ( SELECT * FROM dbo.DatabaseVersionScriptsRun WHERE  DatabaseVersionScriptsRunID = 107  )
 BEGIN

  PRINT 'Creating record for 107.'
  INSERT 
	dbo.DatabaseVersionScriptsRun
	( 
        DatabaseVersionScriptsRunID
        , DatabaseVersionID
        , ScriptName
        , CreatedDate
        , CreatedBy
	)
  VALUES
	( 
	107	-- DatabaseVersionScriptsRunID
	, 100	-- DatabaseVersionID
	, '012.Insert.RockendActions.sql'	-- ScriptName
	, '10 Aug 2011 14:00:00'	-- CreatedDate
	, 0	-- CreatedBy
	)

 END
ELSE
 BEGIN
	PRINT 'Record already exists so not creating; For - 107'
 END


 SET IDENTITY_INSERT dbo.DatabaseVersionScriptsRun OFF
