
/*
NOTE: create manually on AZURE

This file may require some changes for it to work, primarily the FILENAME directory may need changing.

*/

USE [master]
GO

/****** Object:  Database [RestCentral]    Script Date: 08/10/2011 09:46:08 ******/
CREATE DATABASE [RestCentral] ON  PRIMARY 
( NAME = N'Communicator', FILENAME = N'C:\SQL\DATA\RestCentral.mdf' , SIZE = 7424KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'Communicator_log', FILENAME = N'C:\SQL\DATA\RestCentral_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [RestCentral] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RestCentral].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RestCentral] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [RestCentral] SET ANSI_NULLS ON 
GO

ALTER DATABASE [RestCentral] SET ANSI_PADDING ON 
GO

ALTER DATABASE [RestCentral] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [RestCentral] SET ARITHABORT ON 
GO

ALTER DATABASE [RestCentral] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RestCentral] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RestCentral] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RestCentral] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RestCentral] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RestCentral] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [RestCentral] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [RestCentral] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RestCentral] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [RestCentral] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RestCentral] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RestCentral] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RestCentral] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RestCentral] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RestCentral] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RestCentral] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RestCentral] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RestCentral] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RestCentral] SET  READ_WRITE 
GO

ALTER DATABASE [RestCentral] SET RECOVERY FULL 
GO

ALTER DATABASE [RestCentral] SET  MULTI_USER 
GO

ALTER DATABASE [RestCentral] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [RestCentral] SET DB_CHAINING OFF 
GO


