//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Communicator.DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ai8zxgvi72.database.windows.net;Initial Catalog=RestCentralUat;User I" +
            "D=AARockend;Connect Timeout=60")]
        public string RestCentralUatConnectionString {
            get {
                return ((string)(this["RestCentralUatConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=rockend-db-dev.database.windows.net;Initial Catalog=RockendCentral-De" +
            "v;Persist Security Info=True;User ID=rockend-admin@rockend-db-dev;Password=Bvc9P" +
            "8JFj@c47-%e;Connect Timeout=60")]
        public string RockendCentral_UatConnectionString {
            get {
                return ((string)(this["RockendCentral_UatConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=rockend-db-dev.database.windows.net;Initial Catalog=RockendCentral-De" +
            "v;User ID=rockend-admin;Password=Bvc9P8JFj@c47-%e;Encrypt=False;TrustServerCerti" +
            "ficate=True")]
        public string RockendCentral_DevConnectionString {
            get {
                return ((string)(this["RockendCentral_DevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=rockend-db-dev.database.windows.net;Initial Catalog=RockendCentral-Ua" +
            "t;User ID=rockend-admin;Encrypt=True;TrustServerCertificate=False")]
        public string RockendCentral_UatConnectionString1 {
            get {
                return ((string)(this["RockendCentral_UatConnectionString1"]));
            }
        }
    }
}
